const annualAgenda={
  janeiro:[['04','Aniversário do Pr. Sérgio Aquino'],['11','Apresentação de filhos'],['31','Culto RL GO']],
  fevereiro:[['02','Reunião de liderança'],['08','Apresentação de filhos'],['10','Capacitação da liderança Radicais Kids'],['11 e 12','Capacitação de pastores - Goiânia'],['13 e 14','Conferência RL GO'],['16 e 17','Olimpíadas Holy Fest'],['24','Mulheres que Oram'],['24','Início das aulas do Cursão e CTL'],['26 a 28','Jejum de pastores - Supervisão'],['28','Culto RL GO']],
  marco:[['06 a 08','Encontro com Deus'],['08','Apresentação de filhos'],['10','Pós-Encontro'],['12 a 15','Legendários - Rio Verde'],['15/03 a 05/04','Jejum de 21 dias'],['20','Mulheres que Oram'],['28','Culto RL GO']],
  abril:[['03','Início das aulas do Curso de Vida Conjugal'],['10 e 11','Capacitação Videira - Chapadão do Céu'],['12','Apresentação de filhos'],['24','Mulheres que Oram'],['25','Culto RL GO']],
  maio:[['01 e 02','Conferência Vinha Sudoeste'],['04','Reunião de liderança'],['10','Apresentação de filhos'],['15','Mulheres que Oram'],['20','Aniversário da Pra. Joarla'],['23','Culto RL GO'],['30 e 31','Encontro com Deus - Radicais Kids']],
  junho:[['01','Reunião de liderança'],['04 a 06','Conferência de Mulheres - Goiânia'],['12','Jantar de casais'],['14','Apresentação de filhos'],['18 a 21','Legendários - Rio Verde'],['26','Arraiá da Videira'],['29','Mulheres que Oram']],
  julho:[['05','Projeto MT 28'],['10','Mulheres que Oram'],['12','Apresentação de filhos'],['24 a 26','Retiro RL Camp']],
  agosto:[['03','Reunião de liderança'],['07','Capacitação da liderança Radicais Kids'],['09','Apresentação de filhos'],['10','Culto de homens'],['11','Início das aulas do Cursão e CTL'],['14','Início das aulas do Curso de Vida Conjugal'],['21','Mulheres que Oram'],['27 a 29','Jejum de pastores - Supervisão'],['28 a 30','Encontro com Deus']],
  setembro:[['04 e 05','Conferência RL - Goiânia'],['11','Mulheres que Oram'],['13','Apresentação de filhos'],['19','Impacto Radicais Kids e Juvenis'],['20/09 a 11/10','Jejum de 21 dias'],['26','Culto RL GO']],
  outubro:[['02 e 03','Conferência Kids - Rio Verde'],['09','Mulheres que Oram'],['11','Apresentação de filhos'],['15 a 18','Legendários - Rio Verde'],['23 a 25','Encontro de casais - Caldas Novas']],
  novembro:[['02','Reunião de liderança'],['06','Mulheres que Oram'],['08','Apresentação de filhos'],['14','Seminário de Louvor e Adoração - Radicais Kids e Juvenis'],['20 e 21','Conferência RL - Rio Verde'],['27 a 29','Encontro com Deus']],
  dezembro:[['03 a 05','Conferência Internacional Vinha'],['11','Mulheres que Oram'],['12','Festa da Multiplicação'],['13','Apresentação de filhos'],['18','Jantar da Honra - Liderança'],['25','Natal'],['27','Aniversário do Pr. Jozzueh'],['31','Culto da Virada']]
};
const monthLabels={janeiro:'Janeiro',fevereiro:'Fevereiro',marco:'Março',abril:'Abril',maio:'Maio',junho:'Junho',julho:'Julho',agosto:'Agosto',setembro:'Setembro',outubro:'Outubro',novembro:'Novembro',dezembro:'Dezembro'};
const agendaSection=document.getElementById('agenda');
if(agendaSection){
  agendaSection.innerHTML=`<div class="annual-heading"><div><span class="eyebrow">Agenda oficial</span><h2>Agenda Videira 2026</h2><p>Igreja Videira - Chapadão do Céu</p></div><div class="annual-count"><strong>82</strong><span>programações<br>no ano</span></div></div><div class="month-tabs" role="tablist" aria-label="Meses de 2026"></div><div class="month-summary"><div><span id="monthName">Julho</span><small id="monthCount"></small></div><button id="showAllEvents">Ver o ano completo</button></div><div class="annual-events" id="annualEvents"></div>`;
  const tabs=agendaSection.querySelector('.month-tabs');const eventsContainer=document.getElementById('annualEvents');const monthName=document.getElementById('monthName');const monthCount=document.getElementById('monthCount');
  Object.keys(annualAgenda).forEach(key=>{const button=document.createElement('button');button.className='month-tab'+(key==='julho'?' active':'');button.dataset.month=key;button.textContent=monthLabels[key].slice(0,3).toUpperCase();tabs.appendChild(button)});
  function eventCategory(title){const t=title.toLowerCase();if(t.includes('rl')||t.includes('radicais'))return'jovens';if(t.includes('mulher'))return'mulheres';if(t.includes('lider')||t.includes('pastor')||t.includes('capacitação'))return'lideranca';if(t.includes('encontro')||t.includes('conferência')||t.includes('legendários')||t.includes('retiro'))return'evento';return'igreja'}
  function renderMonth(key){monthName.textContent=monthLabels[key];monthCount.textContent=`${annualAgenda[key].length} programações`;eventsContainer.innerHTML=annualAgenda[key].map(([date,title])=>`<article class="annual-event ${eventCategory(title)}"><div class="annual-date"><strong>${date}</strong><span>${monthLabels[key].slice(0,3).toUpperCase()}</span></div><div><span class="event-type">${eventCategory(title)}</span><h3>${title}</h3></div></article>`).join('');document.querySelectorAll('.month-tab').forEach(tab=>tab.classList.toggle('active',tab.dataset.month===key))}
  tabs.addEventListener('click',event=>{if(event.target.matches('.month-tab'))renderMonth(event.target.dataset.month)});
  document.getElementById('showAllEvents').addEventListener('click',()=>{monthName.textContent='Ano completo';monthCount.textContent='Agenda oficial de 2026';eventsContainer.innerHTML=Object.entries(annualAgenda).map(([key,items])=>`<div class="full-month"><h3>${monthLabels[key]}</h3>${items.map(([date,title])=>`<article class="annual-event ${eventCategory(title)}"><div class="annual-date"><strong>${date}</strong><span>${monthLabels[key].slice(0,3).toUpperCase()}</span></div><div><span class="event-type">${eventCategory(title)}</span><h3>${title}</h3></div></article>`).join('')}</div>`).join('');document.querySelectorAll('.month-tab').forEach(tab=>tab.classList.remove('active'))});
  renderMonth('julho');
}
