const menuButton=document.querySelector('.menu-button');const nav=document.querySelector('.nav');menuButton.addEventListener('click',()=>{nav.classList.toggle('open');menuButton.setAttribute('aria-expanded',nav.classList.contains('open'))});nav.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>nav.classList.remove('open')));
const modal=document.getElementById('modal');const content=document.getElementById('modalContent');const templates={word:`<span class="eyebrow">Esboço da semana</span><h2>Aguardando novo esboço</h2><p>O conteúdo da semana será disponibilizado pelo administrador.</p>`,cell:`<span class="eyebrow">Conecte-se</span><h2>Quero participar de uma célula</h2><p>Na versão completa, este formulário enviará seu nome, bairro e telefone para a equipe responsável, que indicará a célula mais próxima.</p><p><strong>Em breve:</strong> cadastro e contato direto pelo WhatsApp da igreja.</p>`};
function openModal(type){content.innerHTML=templates[type];modal.classList.add('open');modal.setAttribute('aria-hidden','false')}document.querySelectorAll('[data-modal]').forEach(b=>b.addEventListener('click',()=>openModal(b.dataset.modal)));document.querySelector('.modal-close').addEventListener('click',()=>modal.classList.remove('open'));modal.addEventListener('click',e=>{if(e.target===modal)modal.classList.remove('open')});document.addEventListener('keydown',e=>{if(e.key==='Escape')modal.classList.remove('open')});
document.getElementById('calendarButton').addEventListener('click',()=>{content.innerHTML='<span class="eyebrow">Agenda mensal</span><h2>Julho de 2026</h2><p>Esta primeira versão apresenta os eventos principais. O calendário administrativo completo será conectado ao banco de dados na próxima etapa.</p>';modal.classList.add('open')});
const defaults={wordTitle:'Aguardando novo esboço',wordVerse:'O conteúdo será publicado pelo desenvolvedor.',wordSummary:'Use o Painel do Desenvolvedor para adicionar o tema, texto bíblico e esboço desta semana.',wordOutline:'O primeiro esboço ainda não foi publicado.',eventTitle:'RL Camp',eventDetails:'Dia 2 • Horário a confirmar'};
let churchContent={...defaults,...JSON.parse(localStorage.getItem('videiraContent')||'{}')};
function renderContent(){document.getElementById('wordTitle').textContent=churchContent.wordTitle;document.getElementById('wordVerse').textContent=churchContent.wordVerse;document.getElementById('wordSummary').textContent=churchContent.wordSummary;document.getElementById('eventTitleCard').textContent=churchContent.eventTitle;document.getElementById('eventDetailsCard').textContent=churchContent.eventDetails;document.getElementById('adminWordTitle').value=churchContent.wordTitle===defaults.wordTitle?'':churchContent.wordTitle;document.getElementById('adminWordVerse').value=churchContent.wordVerse===defaults.wordVerse?'':churchContent.wordVerse;document.getElementById('adminWordSummary').value=churchContent.wordSummary===defaults.wordSummary?'':churchContent.wordSummary;document.getElementById('adminWordOutline').value=churchContent.wordOutline===defaults.wordOutline?'':churchContent.wordOutline;document.getElementById('adminEventTitle').value=churchContent.eventTitle;document.getElementById('adminEventDetails').value=churchContent.eventDetails;templates.word=`<span class="eyebrow">Esboço da semana</span><h2>${escapeHtml(churchContent.wordTitle)}</h2><p><strong>Texto:</strong> ${escapeHtml(churchContent.wordVerse)}</p><div class="outline-text">${escapeHtml(churchContent.wordOutline).replace(/\n/g,'<br>')}</div>`}
function escapeHtml(value){const div=document.createElement('div');div.textContent=value||'';return div.innerHTML}
function saveContent(){localStorage.setItem('videiraContent',JSON.stringify(churchContent));renderContent();const status=document.getElementById('savedStatus');status.textContent='Alterações salvas com sucesso';status.classList.add('flash');setTimeout(()=>{status.textContent='Dados salvos neste navegador';status.classList.remove('flash')},2500)}
document.querySelectorAll('.filter').forEach(button=>button.addEventListener('click',()=>{document.querySelectorAll('.filter').forEach(item=>item.classList.remove('active'));button.classList.add('active');document.querySelectorAll('.cell-card[data-group]').forEach(card=>card.classList.toggle('hidden',card.dataset.group!==button.dataset.filter));const title=document.getElementById('selectedDiscipleship');if(title)title.textContent=button.textContent}));
document.getElementById('wordForm').addEventListener('submit',event=>{event.preventDefault();churchContent.wordTitle=document.getElementById('adminWordTitle').value.trim()||defaults.wordTitle;churchContent.wordVerse=document.getElementById('adminWordVerse').value.trim()||defaults.wordVerse;churchContent.wordSummary=document.getElementById('adminWordSummary').value.trim()||defaults.wordSummary;churchContent.wordOutline=document.getElementById('adminWordOutline').value.trim()||defaults.wordOutline;saveContent()});
document.getElementById('eventForm').addEventListener('submit',event=>{event.preventDefault();churchContent.eventTitle=document.getElementById('adminEventTitle').value.trim()||defaults.eventTitle;churchContent.eventDetails=document.getElementById('adminEventDetails').value.trim()||defaults.eventDetails;saveContent()});
document.getElementById('resetContent').addEventListener('click',()=>{if(confirm('Restaurar os dados iniciais de teste?')){churchContent={...defaults};saveContent()}});renderContent();
const addressData={
 'matheus-costa':['Matheus Costa','Discipulado Matheus','Sábado','Endereço ainda não informado'],
 'matheus-victor':['Matheus Victor','Discipulado Matheus','Quarta-feira','Endereço ainda não informado'],
 'daniel':['Daniel','Discipulado Matheus','Quarta-feira','Endereço ainda não informado'],
 'isadora':['Isadora','Discipulado Matheus','Sábado','Endereço ainda não informado'],
 'klebson':['Klebson','Discipulado Klebson','Sábado','Endereço ainda não informado'],
 'rhayngrid':['Rhayngrid','Discipulado Klebson','Sábado','Endereço ainda não informado'],
 'wiliane':['Wiliane','Discipulado Klebson','Sábado','Endereço ainda não informado'],
 'antonio':['Antônio','Discipulado Antônio','Quarta-feira','Endereço ainda não informado'],
 'humberto':['Humberto','Discipulado Antônio','Quarta-feira','Endereço ainda não informado'],
 'jose-nivolan':['José Nivolan','Discipulado Antônio','Quarta-feira','Endereço ainda não informado'],
 'elimar':['Elimar','Discipulado Antônio','Quarta-feira','Endereço ainda não informado'],
 'edson':['Edson','Discipulado Edson','Quarta-feira','Endereço ainda não informado'],
 'messias':['Messias','Discipulado Edson','Quarta-feira','Endereço ainda não informado'],
 'enio':['Enio','Discipulado Edson','Quarta-feira','Endereço ainda não informado'],
 'celio':['Celio','Discipulado Edson','Quarta-feira','Endereço ainda não informado']
};
const addressSelect=document.getElementById('leaderAddressSelect');function renderAddress(){const data=addressData[addressSelect.value];document.getElementById('addressLeader').textContent=`Célula ${data[0]}`;document.getElementById('addressGroup').textContent=data[1].toUpperCase();document.getElementById('addressDay').textContent=data[2];document.getElementById('addressTime').textContent='19h30';document.getElementById('addressLine').textContent=data[3]}addressSelect.addEventListener('change',renderAddress);renderAddress();
document.querySelectorAll('.leadership-filter').forEach(button=>button.addEventListener('click',()=>{document.querySelectorAll('.leadership-filter').forEach(item=>item.classList.remove('active'));button.classList.add('active');document.querySelectorAll('[data-leadership-group]').forEach(person=>person.classList.toggle('hidden',person.dataset.leadershipGroup!==button.dataset.leadership))}));
const pastoralCards=document.querySelectorAll('.pastoral-leaders>div');const pastorDirectory=document.querySelector('.leadership-directory');if(pastoralCards.length===2&&pastorDirectory){pastoralCards.forEach((card,index)=>{card.setAttribute('role','button');card.setAttribute('tabindex','0');card.setAttribute('aria-pressed',index===0?'true':'false')});pastoralCards[0].classList.add('pastoral-active');const hint=document.createElement('p');hint.className='pastoral-choice-hint';hint.textContent='Clique no pastor ou na pastora para conhecer quem caminha com cada um.';pastorDirectory.before(hint);const pastoraDirectory=document.createElement('div');pastoraDirectory.className='pastora-directory';pastoraDirectory.innerHTML=`<span class="eyebrow">Discipulado da pastora</span><h3>Irmãs, crianças e adolescentes</h3><p class="pastora-intro">Esta área está preparada para receber os nomes das irmãs que caminham com a Pastora Joarla e as equipes responsáveis pelo discipulado das novas gerações.</p><div class="pastora-grid"><article class="pastora-card"><span>IR</span><small>DISCIPULADO</small><h3>Irmãs</h3><p>Nomes das discípulas serão adicionados quando confirmados.</p></article><article class="pastora-card"><span>CR</span><small>NOVA GERAÇÃO</small><h3>Crianças</h3><p>Discipuladores e líderes do ministério infantil serão adicionados.</p></article><article class="pastora-card"><span>AD</span><small>NOVA GERAÇÃO</small><h3>Adolescentes</h3><p>Discipuladores e líderes de adolescentes serão adicionados.</p></article></div><p class="pastora-note">Nenhum nome foi inventado. Os campos aguardam os dados oficiais.</p>`;pastorDirectory.after(pastoraDirectory);function choosePastoral(index){pastoralCards.forEach((card,i)=>{card.classList.toggle('pastoral-active',i===index);card.setAttribute('aria-pressed',i===index?'true':'false')});pastorDirectory.style.display=index===0?'block':'none';pastoraDirectory.classList.toggle('open',index===1)}pastoralCards.forEach((card,index)=>{card.addEventListener('click',()=>choosePastoral(index));card.addEventListener('keydown',event=>{if(event.key==='Enter'||event.key===' '){event.preventDefault();choosePastoral(index)}})})}
