const GROUP_LINKS={jejum:''};
const GROUP_PROJECTS=[
  {kind:'whatsapp',label:'COMUNIDADE',title:'Igreja Videira',description:'Receba avisos, programações e informações importantes da nossa igreja.',button:'Entrar no grupo',url:'https://chat.whatsapp.com/EVu8bd3t0K44R1MT9C1ygR?s=sw&p=i&ilr=4'},
  {kind:'whatsapp',label:'JOVENS',title:'Radicais Livres',description:'Grupo de comunicação dos jovens Radicais Livres.',button:'Entrar no grupo',url:'https://chat.whatsapp.com/Bik8bV3ZplzDfpk2h3GJqG'},
  {kind:'website',label:'PROPÓSITO',title:'21 Dias de Jejum e Oração',description:'Acesse os conteúdos, materiais e informações oficiais do propósito.',button:'Acessar o site',url:'https://jejum21dias.com.br/',whatsappUrl:''}
];
const groupsNav=document.querySelector('.nav');const wordNav=groupsNav?.querySelector('a[href="#palavra"]');
if(groupsNav&&wordNav){const closeGroupsMenu=()=>{groupsNav.classList.remove('open');document.querySelector('.menu-button')?.setAttribute('aria-expanded','false')};const groupsLink=document.createElement('a');groupsLink.href='#grupos';groupsLink.textContent='Grupos';groupsLink.addEventListener('click',closeGroupsMenu);const fastingLink=document.createElement('a');fastingLink.href='#jejum21';fastingLink.textContent='21 Dias';fastingLink.addEventListener('click',closeGroupsMenu);groupsNav.insertBefore(groupsLink,wordNav);groupsNav.insertBefore(fastingLink,wordNav)}
const groupIcon=kind=>kind==='whatsapp'?`<svg viewBox="0 0 32 32" aria-hidden="true"><path fill="currentColor" d="M16 3a12 12 0 0 0-10.4 18l-1.7 6.2 6.4-1.7A12 12 0 1 0 16 3Zm0 21.8c-1.9 0-3.6-.5-5.1-1.4l-.4-.2-3.8 1 1-3.7-.2-.4A9.7 9.7 0 1 1 16 24.8Zm5.3-7.3c-.3-.1-1.7-.8-2-.9-.3-.1-.5-.1-.7.2l-.9 1.1c-.2.2-.3.2-.6.1-1.8-.7-3.1-2-4-3.6-.2-.3 0-.5.1-.6l.6-.7c.2-.2.2-.4.3-.6 0-.2 0-.4-.1-.6l-.9-2.1c-.2-.5-.5-.5-.7-.5h-.6c-.2 0-.6.1-.9.4-.3.3-1.2 1.2-1.2 2.9s1.2 3.3 1.4 3.5c.2.2 2.4 3.7 5.9 5.1.8.4 1.5.6 2 .7.9.3 1.7.2 2.3.1.7-.1 2-1 2.3-1.6.3-.6.3-1.2.2-1.3-.1-.1-.3-.2-.6-.3Z"/></svg>`:`<svg viewBox="0 0 32 32" aria-hidden="true"><path fill="none" stroke="currentColor" stroke-width="2.2" stroke-linecap="round" stroke-linejoin="round" d="M12 20 24 8m-8 0h8v8M22 19v6H7V10h6"/></svg>`;
const groupsSection=document.createElement('section');groupsSection.id='grupos';groupsSection.className='section groups-section';groupsSection.innerHTML=`<div class="section-heading"><div><span class="eyebrow">Caminhe com a gente</span><h2>Grupos e projetos</h2><p class="section-intro">Acesse os canais e projetos oficiais da Igreja Videira.</p></div></div><div class="group-cards">${GROUP_PROJECTS.map(item=>`<article class="group-card"><span class="group-icon ${item.kind}">${groupIcon(item.kind)}</span><div class="group-card-content"><small>${item.label}</small><h3>${item.title}</h3><p>${item.description}</p></div><a class="group-access ${item.kind}" href="${item.url}" target="_blank" rel="noopener noreferrer">${item.button}<span aria-hidden="true">↗</span></a></article>`).join('')}</div>`;
const fastingSection=document.createElement('section');fastingSection.id='jejum21';fastingSection.className='fasting-section';fastingSection.innerHTML=`<div class="fasting-hero"><span class="eyebrow">Um tempo de consagração</span><h2>21 Dias de Jejum e Oração</h2><p>Separe este período para buscar a Deus, fortalecer sua fé e caminhar em unidade com a igreja.</p><div class="fasting-dates">Datas oficiais serão confirmadas</div>${GROUP_LINKS.jejum?`<a href="${GROUP_LINKS.jejum}" target="_blank" rel="noopener">Participar do grupo</a>`:''}</div><div class="fasting-materials"><div class="materials-heading"><div><span class="eyebrow">Acompanhamento diário</span><h3>Materiais do propósito</h3></div><label>Selecionar dia<select id="fastingDayFilter"><option value="all">Todos os dias</option>${Array.from({length:21},(_,i)=>`<option value="${i+1}">Dia ${i+1}</option>`).join('')}</select></label></div><div id="fastingFiles" class="fasting-files"><p>Carregando materiais...</p></div></div>`;
const agenda=document.getElementById('agenda');agenda?.after(groupsSection,fastingSection);
const adminGrid=document.querySelector('#admin .admin-grid');if(adminGrid){const form=document.createElement('form');form.className='admin-card fasting-admin';form.id='fastingUploadForm';form.innerHTML=`<h3>Material dos 21 Dias</h3><label>Título<input id="fastingTitle" placeholder="Ex.: Devocional - Dia 1" required></label><label>Dia do propósito<select id="fastingDay"><option value="">Material geral</option>${Array.from({length:21},(_,i)=>`<option value="${i+1}">Dia ${i+1}</option>`).join('')}</select></label><label class="fasting-file-label">PDF ou imagem<input type="file" id="fastingFile" accept=".pdf,.jpg,.jpeg,.png,.webp,application/pdf,image/jpeg,image/png,image/webp" required></label><button class="button primary" type="submit">Publicar material</button><p id="fastingUploadStatus"></p></form>`;adminGrid.appendChild(form)}
let fastingItems=[];function fastingUrl(item){return sb.storage.from('jejum').getPublicUrl(item.storage_path).data.publicUrl}function renderFasting(){const filter=document.getElementById('fastingDayFilter').value;const selected=fastingItems.filter(item=>filter==='all'||String(item.dia_campanha)===filter);const box=document.getElementById('fastingFiles');box.innerHTML=selected.length?selected.map(item=>{const url=fastingUrl(item),isImage=item.mime_type?.startsWith('image/');return`<article class="fasting-file">${isImage?`<img src="${url}" alt="${safeText(item.titulo)}">`:`<span class="pdf-icon">PDF</span>`}<div><small>${item.dia_campanha?`DIA ${item.dia_campanha}`:'MATERIAL GERAL'}</small><h4>${safeText(item.titulo)}</h4><p>${safeText(item.arquivo_nome)}</p></div><div class="fasting-actions"><a href="${url}" target="_blank" rel="noopener">Abrir</a><a href="${url}?download=${encodeURIComponent(item.arquivo_nome)}">Baixar</a><button data-fasting-delete="${item.id}" data-fasting-path="${safeText(item.storage_path)}">Excluir</button></div></article>`}).join(''):'<div class="fasting-empty"><strong>Nenhum material neste período</strong><p>Os PDFs e imagens aparecerão aqui quando forem publicados.</p></div>'}
async function loadFasting(){const{data,error}=await sb.from('jejum_materiais').select('*').order('dia_campanha',{ascending:true,nullsFirst:true});if(error){document.getElementById('fastingFiles').innerHTML='<div class="fasting-empty"><strong>Configuração pendente</strong><p>Execute o SQL dos 21 Dias no Supabase.</p></div>';return}fastingItems=data;renderFasting()}document.getElementById('fastingDayFilter').addEventListener('change',renderFasting);loadFasting();
document.getElementById('fastingUploadForm')?.addEventListener('submit',async event=>{event.preventDefault();const status=document.getElementById('fastingUploadStatus');const file=document.getElementById('fastingFile').files[0],title=document.getElementById('fastingTitle').value.trim(),day=document.getElementById('fastingDay').value;if(!currentSession||currentSession.user.email.toLowerCase()!==ADMIN_EMAIL)return alert('Entre como administrador.');if(file.size>15*1024*1024)return alert('O arquivo deve ter no máximo 15 MB.');status.textContent='Publicando...';const clean=file.name.normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-zA-Z0-9._-]/g,'-');const path=`campanha/${Date.now()}-${clean}`;const upload=await sb.storage.from('jejum').upload(path,file,{contentType:file.type});if(upload.error){status.textContent=upload.error.message;return}const insert=await sb.from('jejum_materiais').insert({titulo:title,dia_campanha:day?Number(day):null,arquivo_nome:file.name,storage_path:path,mime_type:file.type});if(insert.error){await sb.storage.from('jejum').remove([path]);status.textContent=insert.error.message}else{event.target.reset();status.textContent='Material publicado para todos.';loadFasting()}});
document.getElementById('fastingFiles').addEventListener('click',async event=>{if(!event.target.dataset.fastingDelete)return;if(!currentSession||currentSession.user.email.toLowerCase()!==ADMIN_EMAIL)return;if(!confirm('Excluir este material?'))return;await sb.storage.from('jejum').remove([event.target.dataset.fastingPath]);await sb.from('jejum_materiais').delete().eq('id',event.target.dataset.fastingDelete);loadFasting()});
