const wordFilters=document.createElement('div');wordFilters.className='word-filters';wordFilters.innerHTML=`<label>Ano<select id="wordYearFilter"><option value="all">Todos</option></select></label><label>Mês<select id="wordMonthFilter"><option value="all">Todos</option></select></label><label>Semana<select id="wordWeekFilter"><option value="all">Todas</option></select></label><button id="clearWordFilters">Limpar filtros</button>`;
document.querySelector('.cloud-heading')?.after(wordFilters);
let onlineWords=[];
function wordPublicUrl(item){return sb.storage.from('palavras').getPublicUrl(item.storage_path).data.publicUrl}
function formatOnlineRange(start,end){const a=new Date(start+'T12:00:00'),b=new Date(end+'T12:00:00');return`${String(a.getDate()).padStart(2,'0')} a ${String(b.getDate()).padStart(2,'0')} de ${b.toLocaleDateString('pt-BR',{month:'long'})}`}
function updateLatestWord(){if(!onlineWords.length)return;const latest=onlineWords[0];const title=document.getElementById('wordTitle');const verse=document.getElementById('wordVerse');const summary=document.getElementById('wordSummary');if(title)title.textContent=latest.titulo;if(verse)verse.textContent=`Palavra da semana • ${formatOnlineRange(latest.semana_inicio,latest.semana_fim)}`;if(summary)summary.textContent='O esboço completo está disponível em PDF ou Word para abrir e baixar.';const oldButton=document.querySelector('#palavra [data-modal="word"]');if(oldButton){const link=document.createElement('a');link.className=oldButton.className;link.textContent='Abrir Palavra da semana';link.href=wordPublicUrl(latest);link.target='_blank';link.rel='noopener';oldButton.replaceWith(link)}}
function fillWordFilters(){const year=document.getElementById('wordYearFilter'),month=document.getElementById('wordMonthFilter'),week=document.getElementById('wordWeekFilter');const years=[...new Set(onlineWords.map(item=>item.semana_inicio.slice(0,4)))];year.innerHTML='<option value="all">Todos</option>'+years.map(value=>`<option>${value}</option>`).join('');const months=[...new Set(onlineWords.map(item=>item.semana_inicio.slice(0,7)))].sort().reverse();month.innerHTML='<option value="all">Todos</option>'+months.map(value=>{const date=new Date(value+'-15T12:00:00');return`<option value="${value}">${date.toLocaleDateString('pt-BR',{month:'long',year:'numeric'})}</option>`}).join('');week.innerHTML='<option value="all">Todas</option>'+onlineWords.map(item=>`<option value="${item.id}">${formatOnlineRange(item.semana_inicio,item.semana_fim)} — ${safeText(item.titulo)}</option>`).join('')}
function renderFilteredWords(){const year=document.getElementById('wordYearFilter').value,month=document.getElementById('wordMonthFilter').value,week=document.getElementById('wordWeekFilter').value;const selected=onlineWords.filter(item=>(year==='all'||item.semana_inicio.startsWith(year))&&(month==='all'||item.semana_inicio.startsWith(month))&&(week==='all'||String(item.id)===week));const container=document.getElementById('cloudWords');container.innerHTML=selected.length?selected.map(item=>{const url=wordPublicUrl(item);return`<article class="cloud-word"><div class="cloud-date"><small>SEMANA</small><strong>${formatOnlineRange(item.semana_inicio,item.semana_fim)}</strong></div><div class="cloud-document"><span>${item.arquivo_nome.split('.').pop().toUpperCase()}</span><div><h3>${safeText(item.titulo)}</h3><p>${safeText(item.arquivo_nome)}</p></div></div><div class="cloud-actions"><a href="${url}" target="_blank" rel="noopener">Abrir</a><a href="${url}?download=${encodeURIComponent(item.arquivo_nome)}">Baixar</a><button data-cloud-delete="${item.id}" data-storage-path="${safeText(item.storage_path)}">Excluir</button></div></article>`}).join(''):'<div class="cloud-empty"><strong>Nenhuma Palavra encontrada</strong><p>Altere os filtros para consultar outro período.</p></div>'}
async function loadEnhancedWords(){const{data,error}=await sb.from('palavras').select('*').order('semana_inicio',{ascending:false});if(error)return;onlineWords=data;fillWordFilters();updateLatestWord();renderFilteredWords()}
['wordYearFilter','wordMonthFilter','wordWeekFilter'].forEach(id=>document.getElementById(id)?.addEventListener('change',renderFilteredWords));document.getElementById('clearWordFilters')?.addEventListener('click',()=>{['wordYearFilter','wordMonthFilter','wordWeekFilter'].forEach(id=>document.getElementById(id).value='all');renderFilteredWords()});
document.getElementById('saveCloudWord')?.addEventListener('click',()=>setTimeout(loadEnhancedWords,1800));
setTimeout(loadEnhancedWords,500);
