-- Execute uma única vez no SQL Editor, após o supabase-setup.sql.
create table if not exists public.jejum_materiais (
  id bigint generated by default as identity primary key,
  titulo text not null,
  dia_campanha integer,
  arquivo_nome text not null,
  storage_path text not null unique,
  mime_type text,
  created_at timestamptz not null default now(),
  constraint dia_campanha_valido check (dia_campanha is null or dia_campanha between 1 and 21)
);
alter table public.jejum_materiais enable row level security;
grant select on public.jejum_materiais to anon, authenticated;
grant insert, update, delete on public.jejum_materiais to authenticated;
grant usage, select on sequence public.jejum_materiais_id_seq to authenticated;
drop policy if exists "Materiais do jejum visiveis para todos" on public.jejum_materiais;
create policy "Materiais do jejum visiveis para todos" on public.jejum_materiais for select to anon, authenticated using (true);
drop policy if exists "Administrador insere materiais do jejum" on public.jejum_materiais;
create policy "Administrador insere materiais do jejum" on public.jejum_materiais for insert to authenticated with check ((select auth.jwt()->>'email')='matheus.costa71@outlook.com');
drop policy if exists "Administrador exclui materiais do jejum" on public.jejum_materiais;
create policy "Administrador exclui materiais do jejum" on public.jejum_materiais for delete to authenticated using ((select auth.jwt()->>'email')='matheus.costa71@outlook.com');
insert into storage.buckets(id,name,public,file_size_limit,allowed_mime_types) values('jejum','jejum',true,15728640,array['application/pdf','image/jpeg','image/png','image/webp']) on conflict(id) do update set public=true,file_size_limit=15728640,allowed_mime_types=array['application/pdf','image/jpeg','image/png','image/webp'];
drop policy if exists "Materiais do jejum sao publicos" on storage.objects;
create policy "Materiais do jejum sao publicos" on storage.objects for select to anon, authenticated using(bucket_id='jejum');
drop policy if exists "Administrador envia materiais do jejum" on storage.objects;
create policy "Administrador envia materiais do jejum" on storage.objects for insert to authenticated with check(bucket_id='jejum' and (select auth.jwt()->>'email')='matheus.costa71@outlook.com');
drop policy if exists "Administrador exclui materiais do jejum" on storage.objects;
create policy "Administrador exclui materiais do jejum" on storage.objects for delete to authenticated using(bucket_id='jejum' and (select auth.jwt()->>'email')='matheus.costa71@outlook.com');
