-- Execute uma única vez no SQL Editor do projeto Igreja Videira.
create table if not exists public.palavras (
  id bigint generated by default as identity primary key,
  titulo text not null,
  semana_inicio date not null,
  semana_fim date not null,
  arquivo_nome text not null,
  storage_path text not null unique,
  mime_type text,
  created_at timestamptz not null default now(),
  constraint semana_valida check (semana_fim >= semana_inicio)
);

alter table public.palavras enable row level security;
grant select on public.palavras to anon, authenticated;
grant insert, update, delete on public.palavras to authenticated;
grant usage, select on sequence public.palavras_id_seq to authenticated;

drop policy if exists "Palavras visiveis para todos" on public.palavras;
create policy "Palavras visiveis para todos" on public.palavras
for select to anon, authenticated using (true);

drop policy if exists "Somente administrador insere palavras" on public.palavras;
create policy "Somente administrador insere palavras" on public.palavras
for insert to authenticated with check ((select auth.jwt()->>'email') = 'matheus.costa71@outlook.com');

drop policy if exists "Somente administrador atualiza palavras" on public.palavras;
create policy "Somente administrador atualiza palavras" on public.palavras
for update to authenticated using ((select auth.jwt()->>'email') = 'matheus.costa71@outlook.com')
with check ((select auth.jwt()->>'email') = 'matheus.costa71@outlook.com');

drop policy if exists "Somente administrador exclui palavras" on public.palavras;
create policy "Somente administrador exclui palavras" on public.palavras
for delete to authenticated using ((select auth.jwt()->>'email') = 'matheus.costa71@outlook.com');

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('palavras', 'palavras', true, 15728640, array['application/pdf','application/msword','application/vnd.openxmlformats-officedocument.wordprocessingml.document'])
on conflict (id) do update set public=true, file_size_limit=15728640,
allowed_mime_types=array['application/pdf','application/msword','application/vnd.openxmlformats-officedocument.wordprocessingml.document'];

drop policy if exists "Arquivos de palavras sao publicos" on storage.objects;
create policy "Arquivos de palavras sao publicos" on storage.objects
for select to anon, authenticated using (bucket_id = 'palavras');

drop policy if exists "Administrador envia arquivos" on storage.objects;
create policy "Administrador envia arquivos" on storage.objects
for insert to authenticated with check (bucket_id = 'palavras' and (select auth.jwt()->>'email') = 'matheus.costa71@outlook.com');

drop policy if exists "Administrador atualiza arquivos" on storage.objects;
create policy "Administrador atualiza arquivos" on storage.objects
for update to authenticated using (bucket_id = 'palavras' and (select auth.jwt()->>'email') = 'matheus.costa71@outlook.com');

drop policy if exists "Administrador exclui arquivos" on storage.objects;
create policy "Administrador exclui arquivos" on storage.objects
for delete to authenticated using (bucket_id = 'palavras' and (select auth.jwt()->>'email') = 'matheus.costa71@outlook.com');
